version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: miniwall-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
